language: node_js
node_js:
  - '8.9'

cache:
  directories:
    - node_modules

install:
  - npm install -g codecov
  - npm install

script:
  - npm run test
  - codecov

notifications:
  email:
    on_success: never
    on_failure: change